contact_email: contact@coops.tech
collections:
  coops:
    output: true
    permalink: /co-op/:name
  clients:
    output: false
  services:
    output: true
    permalink: /service/:name
  technologies:
    output: true
    permalink: /technology/:name
defaults:
  - scope:
      type: coops
    values:
      layout: co-op
  - scope:
      type: services
    values:
      layout: service
